export const CHANGE_CUSTOMER = 'COD_CHANGE_CUSTOMER';
export const ADD_PRODUCT = 'COD_ADD_PRODUCT';
export const UPDATE_PRODUCT_QUANTITY = 'COD_UPDATE_PRODUCT_QUANTITY';
export const UPDATE_PRODUCT_TOTAL = 'COD_UPDATE_PRODUCT_TOTAL';
export const REMOVE_PRODUCT = 'COD_REMOVE_PRODUCT';
export const CHANGE_DESCRIPTION = 'COD_CHANGE_DESCRIPTION';
