version: '3.6'

services: 
  server:
    container_name: server
    build: ./server
    ports: 
      - "3001:3001"
    image: lusanney/thuyserver
  client:
    container_name: client
    build: ./client
    stdin_open: true
    ports: 
      - "80:80"
    image: lusanney/thuyclient