export const ADD_PRODUCT = 'CS_ADD_PRODUCT';
export const UPDATE_PRODUCT_QUANTITY = 'CS_UPDATE_PRODUCT_QUANTITY';
export const UPDATE_PRODUCT_TOTAL = 'CS_UPDATE_PRODUCT_TOTAL';
export const REMOVE_PRODUCT = 'CS_REMOVE_PRODUCT';
